### ISSUE TITLE
Remove "Go to home page" word from modal

### ISSUE THREAD

**Issue by behruz-b** [behruz-b/medical#23]
Need to put button with text "Yopish"
![image](https://user-images.githubusercontent.com/9760140/104082332-2cab7a80-5257-11eb-9416-1c43aa22c193.png)

**Comment by yunusbek1710** [comment]
The word "go to home page" removed

**Comment by behruz-b** [comment]
Need to add button "Yopish" instead of "Bosh sahifaga"
![image](https://user-images.githubusercontent.com/9760140/104093977-dcacd200-52af-11eb-9f8d-c9a6c50b27eb.png)

**Comment by yunusbek1710** [comment]
#23 closed
