### ISSUE TITLE
Lang should be at the last of address (routes)

### ISSUE THREAD

**Issue by behruz-b** [behruz-b/medical#28]
![image](https://user-images.githubusercontent.com/9760140/104084361-2d004180-5268-11eb-8134-6bb8a9f6de2c.png)
### Should be:
../admin -> ../admin?lang=uz
../admin?lang=ru -> ../admin?lang=ru
../admin?lang=en -> ../admin?lang=en

Default should be uz

**Comment by yunusbek1710** [comment]
#28 closed
