### ISSUE TITLE
Admin form: couldn't create statistics role

### ISSUE THREAD

**Issue by behruz-b** [behruz-b/medical#96]
![image](https://user-images.githubusercontent.com/9760140/105800719-37853f80-5fb9-11eb-80aa-a4b8c6d20b01.png)

![image](https://user-images.githubusercontent.com/9760140/105800792-67344780-5fb9-11eb-8db4-c70edb79f44b.png)

**Comment by Bekturdi** [comment]
Admin form: roles get DB
